# Generated by Django 2.2.4 on 2021-05-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojo',
            old_name='Name',
            new_name='name',
        ),
    ]
